name: cosyvoice
# LLM: integrated modelscope for Qwen2.5VL calling
# TTS: integrated edge_tts & cosyvoice requirements.txt 
# THG: integrated musetalk requirements.txt 

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - opencv>=4.9.0
  # Conda packages from original file
  - numpy # Updated from new list
  - pillow>=10.0.0
  - python-dotenv>=1.0.0
  # New/Updated conda packages
  - diffusers==0.30.2 # Updated from new list
  - fastapi==0.115.6
  - gdown # Version updated from new list
  - gradio>=5.0.0 # Updated from new list
  - grpcio
  - grpcio-tools
  - hydra-core==1.3.2
  - inflect==7.3.1
  - librosa==0.11.0 # Updated from new list
  - lightning==2.2.4
  - matplotlib>=3.7.0
  - networkx==3.1
  - omegaconf # Version updated from new list
  - openai>=1.0.0
  - pyarrow>=18.1.0
  - pydantic==2.7.0
  - rich==13.7.1
  - pysoundfile==0.12.1 # Renamed from soundfile
  - tensorboard==2.12.0 # Updated from new list
  - transformers==4.39.2 # Updated from new list
  - uvicorn==0.30.0
  - huggingface_hub==0.30.2 # New
  - requests # New
  - imageio # New
  - moviepy # New
  # Packages moved from pip
  - accelerate==0.28.0
  - einops==0.8.1
  - ffmpeg-python
  - pyworld==0.3.4
  - pip:
    - --index-url https://download.pytorch.org/whl/cu128
    - --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
    # Torch packages
    - torch
    - torchvision
    - torchaudio
    # Pip-only packages
    - tensorflow==2.12.0 # Why musetalk want tensorflow?
    - wget==3.2
    - protobuf==4.25
    - edge-tts>=6.1.0
    - conformer==0.3.2
    - deepspeed==0.15.1; sys_platform == 'linux'
    - fastapi-cli==0.0.4
    - HyperPyYAML==1.2.2
    - modelscope==1.20.0
    - onnx==1.16.0
    - onnxruntime-cuda==1.18.0; sys_platform == 'linux'
    - onnxruntime==1.18.0; sys_platform == 'darwin' or sys_platform == 'win32'
    - openai-whisper==20231117
    - tensorrt-cu12==10.0.1; sys_platform == 'linux'
    - tensorrt-cu12-bindings==10.0.1; sys_platform == 'linux'
    - tensorrt-cu12-libs==10.0.1; sys_platform == 'linux'
    - wetext==0.0.4
