name: SoCommVoice
# LLM: integrated modelscope for Qwen2.5VL calling
# TTS: integrated edge_tts & cosyvoice requirements.txt 
# THG: integrated musetalk requirements.txt 

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - opencv>=4.9.0
  # Conda packages from original file
  - numpy # Updated from new list
  - pillow>=10.0.0
  - python-dotenv>=1.0.0
  # New/Updated conda packages
  - diffusers==0.30.2 # Updated from new list
  - fastapi==0.115.6
  - gdown # Version updated from new list
  # - gradio>=5.0.0 # Updated from new list
  - grpcio
  - grpcio-tools
  - hydra-core==1.3.2
  - inflect==7.3.1
  - librosa==0.11.0 # Updated from new list
  - lightning==2.2.4
  - matplotlib>=3.7.0
  - networkx==3.1
  - omegaconf # Version updated from new list
  - openai>=1.0.0
  - pydantic==2.7.0
  - rich==13.7.1
  - pysoundfile==0.12.1 # Renamed from soundfile
  - tensorboard>=2.16.1 # Updated from new list
  - transformers==4.39.2 # Updated from new list
  - uvicorn==0.30.0
  - huggingface_hub==0.30.2 # New
  - requests # New
  - imageio # New
  - moviepy # New
  # Packages moved from pip
  - accelerate==0.28.0
  - einops==0.8.1
  - ffmpeg-python
  - pyworld==0.3.4
  # - tensorflow-gpu>=2.16.0
  - protobuf>=4.25
  - deepspeed>=0.15.1
  - fastapi-cli>=0.0.4
  - onnxruntime>=1.19.2
  - onnx
  #paddlespeech required 
  - libsndfile 
  - bzip2
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
    # Torch packages
    - torch==2.1.2 # downgrade to fit mmcv2.1.0
    - torchvision==0.16.2
    - torchaudio==2.1.2
    
    # pip prefered package 
    - tensorflow==2.12.0

    # Pip-only packages
    - edge-tts>=6.1.0
    - conformer==0.3.2
    - HyperPyYAML==1.2.2
    - modelscope==1.20.0
    # - onnx==1.16.0
    # - onnxruntime-gpu>=1.18.0; sys_platform == 'linux'
    # - onnxruntime>=1.18.0; sys_platform == 'darwin' or sys_platform == 'win32'
    - openai-whisper==20231117
    - tensorrt-cu12==10.0.1; sys_platform == 'linux'
    - tensorrt-cu12-bindings==10.0.1; sys_platform == 'linux'
    - tensorrt-cu12-libs==10.0.1; sys_platform == 'linux'
    - wetext==0.0.4

    # paddle tts support (only pip)
    - pytest-runner
    - g2pM
    - flatten_dict
    - jsonlines
    - kaldiio
    - loguru
    - nara-wpe
    - paddlespeech-feat
    - pathos
    - ppdiffusers>=0.9.0
    - pyloudnorm
    - resampy
    - sacrebleu
    # - g2pen 
    - editdistance
    - aistudio-sdk==0.2.6
    
    # failed to install via conda (run-time error)
    - pyarrow==18.1.0
    - gradio==5.4.0
    # cosyvoice require pypi version wget
    - wget

    # MuseTalk require pypi version 
    - huggingface_hub[cli]

    # # mockingbird require 
    # - sounddevice
    # - SoundFile
    # - PyWavelets
    # - torch_complex
    # - espent
    # - umap-learn
    # - monotonic-align==1.0.0
    # - unidecode

